# fly.toml app configuration file generated for thecodingtemple on 2023-07-18T09:58:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "thecodingtemple"
primary_region = "yyz"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
